console.log('hello');
let a=window;
// window.alert('hello kashaf');
// // or
// alert("hello kashaf");

// no need to write window because it is global object in client site javascript
// so we can write all methods of windows without using windows

// a=prompt('This will destroy you system');

a=confirm('Are u wannt to delete this page?');//gives answer in boolean

console.log(window.document);
console.log(window.innerHeight);


console.log(window.innerWidth);
// or
console.log(innerHeight);
console.log(scrollX);
console.log(scrollY);

console.log(location);

// console.log(location.href='//codewithharry.com');

console.log(location.toString())//will show location in string

console.log(location.history);
console.log(history.length());
console.log(history.go(-1))//will take you the location where you were working on this before
console.log(history.go(1))//go ahead




console.log(a);


